name: fraud-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.25.0
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - scikit-learn==1.2.2
      - xgboost==1.7.6
      - lightgbm==3.3.5
      - catboost==1.2
