name: fraud-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.4
  - scikit-learn=1.2.2
  - pandas
  - matplotlib
  - seaborn
  - xgboost=1.7.6
  - lightgbm=3.3.5
  - catboost=1.2
  - pip
  - pip:
      - streamlit==1.27.2
