name: fraud-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - scikit-learn=1.3.2   # or the latest stable version
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - xgboost
  - lightgbm
  - catboost=1.2
