name: fraud-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit>=1.25.0
      - pandas
      - numpy
      - scikit-learn==1.2.2
      - xgboost==1.7.6
      - lightgbm==3.3.5
      - catboost==1.0.6
      - matplotlib
      - seaborn
      - shap==0.41.0
      - numba==0.53.1
      - llvmlite==0.36.0
      - streamlit-extras
