name: multi-fraud-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn=1.2.2
  - pip
  - pip:
      - streamlit>=1.25.0
      - xgboost==1.7.6
      - lightgbm==3.3.5
      - catboost==1.2
      - shap
