name: fraud-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - xgboost=1.7.6
  - lightgbm=3.3.5
  - catboost=1.2
  - streamlit=1.24.0
  - shap=0.41.0
  - pip
  - pip:
      - joblib
      - tqdm
