name: fraud-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scikit-learn==1.2.2
  - pip:
      - streamlit>=1.25.0
      - xgboost==1.7.6
      - lightgbm==3.3.5
      - catboost==1.0.6
      - shap==0.41.0
      - numba==0.53.1
      - llvmlite==0.36.0
      - streamlit-extras
